spring.application.name=movie.info.service
server.port=8082
movieDB.api.key=bde537400cfa9e6f8ad805e604c892bd
#eureka.client.service-url.http://localhost:8080/
#eureka.client.eureka-server-port=8080
#eureka.client.eureka-server-u-r-l-context=http://localhost:8080/


